---
dependency:
  name: galaxy
driver:
  name: vagrant
platforms:
  - name: k8s-master
    box: centos/7
    memory: 512
    cpus: 1
  - name: k8s-worker1
    box: centos/7
    memory: 512
    cpus: 1
  - name: k8s-worker2
    box: centos/7
    memory: 512
    cpus: 1
provisioner:
  name: ansible
  inventory:
    hosts:
      master:
        hosts:
          k8s-master:
      worker:
        hosts:
          k8s-worker1:
          k8s-worker2:
scenario:
  test_sequence:
    - dependency
    - lint
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - verify
    - cleanup
    - destroy
verifier:
  name: ansible
